// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {repo} from '../models';

export function GetStatus(arg1:string):Promise<repo.Status>;

export function List():Promise<Array<repo.BasicDetails>>;

export function StartRepo(arg1:string):Promise<void>;

export function StopRepo(arg1:string):Promise<void>;
