// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetStatus(arg1) {
  return window['go']['repobrowser']['RepoBrowser']['GetStatus'](arg1);
}

export function List() {
  return window['go']['repobrowser']['RepoBrowser']['List']();
}

export function RegisterRunningRepoStatusWatcher(arg1) {
  return window['go']['repobrowser']['RepoBrowser']['RegisterRunningRepoStatusWatcher'](arg1);
}

export function StartRepo(arg1) {
  return window['go']['repobrowser']['RepoBrowser']['StartRepo'](arg1);
}

export function Startup(arg1) {
  return window['go']['repobrowser']['RepoBrowser']['Startup'](arg1);
}

export function StopRepo(arg1) {
  return window['go']['repobrowser']['RepoBrowser']['StopRepo'](arg1);
}
