// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {repobrowser} from '../models';

export function ListRepos(arg1:repobrowser.ListReposOptions):Promise<Array<repobrowser.RepoInfo>>;

export function StartRepo(arg1:string):Promise<void>;

export function StopRepo(arg1:string):Promise<void>;
