// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetRepoRepoStatusNotificationChannel(arg1) {
  return window['go']['repobrowser']['RepoBrowser']['GetRepoRepoStatusNotificationChannel'](arg1);
}

export function GetRepoStatus(arg1) {
  return window['go']['repobrowser']['RepoBrowser']['GetRepoStatus'](arg1);
}

export function InitRepos() {
  return window['go']['repobrowser']['RepoBrowser']['InitRepos']();
}

export function ListRepos() {
  return window['go']['repobrowser']['RepoBrowser']['ListRepos']();
}

export function RegisterRepoStatusWatcher(arg1) {
  return window['go']['repobrowser']['RepoBrowser']['RegisterRepoStatusWatcher'](arg1);
}

export function StartRepo(arg1) {
  return window['go']['repobrowser']['RepoBrowser']['StartRepo'](arg1);
}

export function Startup(arg1) {
  return window['go']['repobrowser']['RepoBrowser']['Startup'](arg1);
}

export function StopRepo(arg1) {
  return window['go']['repobrowser']['RepoBrowser']['StopRepo'](arg1);
}
