// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {repo} from '../models';
import {context} from '../models';

export function GetRepoRepoStatusNotificationChannel(arg1:string):Promise<string>;

export function GetRepoStatus(arg1:string):Promise<repo.Status>;

export function InitRepos():Promise<void>;

export function ListRepos():Promise<Array<repo.BasicDetails>>;

export function RegisterRepoStatusWatcher(arg1:string):Promise<void>;

export function StartRepo(arg1:string):Promise<void>;

export function Startup(arg1:context.Context):Promise<void>;

export function StopRepo(arg1:string):Promise<void>;
