// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetEnvParamOverrides() {
  return window['go']['app']['Settings']['GetEnvParamOverrides']();
}

export function GetSettings() {
  return window['go']['app']['Settings']['GetSettings']();
}

export function SaveEnvParamOverrides(arg1) {
  return window['go']['app']['Settings']['SaveEnvParamOverrides'](arg1);
}

export function SaveSettings(arg1) {
  return window['go']['app']['Settings']['SaveSettings'](arg1);
}

export function Startup(arg1) {
  return window['go']['app']['Settings']['Startup'](arg1);
}
